# Generated by Django 6.0.3 on 2026-06-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('percentage', models.PositiveIntegerField()),
                ('color', models.CharField(choices=[('#3B5BDB', 'Blue'), ('#8B5CF6', 'Purple'), ('#F43F5E', 'Pink'), ('#F4B000', 'Yellow'), ('#10B981', 'Green')], max_length=20)),
                ('center_image', models.ImageField(blank=True, null=True, upload_to='expense_center/')),
            ],
        ),
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recent_activity/')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=50)),
            ],
        ),
    ]
