# Generated by Django 6.0.3 on 2026-06-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0002_expensebreakdown_recentactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='transactions/')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
