# Generated by Django 6.0.3 on 2026-06-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0004_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='transactions/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Card', 'Card'), ('Cash', 'Cash')], max_length=30, null=True),
        ),
    ]
