# Generated by Django 6.0.3 on 2026-06-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0006_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
