# Generated by Django 6.0.3 on 2026-06-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0007_bill_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='bills/'),
        ),
    ]
