# Generated by Django 6.0.3 on 2026-06-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0008_bill_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='expense_categories/')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', models.PositiveIntegerField()),
                ('category_type', models.CharField(choices=[('food', 'Food'), ('shopping', 'Shopping'), ('bills', 'Bills & Utilities'), ('transport', 'Transportation'), ('entertainment', 'Entertainment')], max_length=20, unique=True)),
            ],
            options={
                'ordering': ['-percentage'],
            },
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Expired', 'Expired')], default='Pending', max_length=20),
        ),
    ]
