# Generated by Django 6.0.3 on 2026-06-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0009_expensecategory_alter_bill_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('point_1', models.CharField(max_length=255)),
                ('point_2', models.CharField(blank=True, max_length=255)),
                ('point_3', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TopSpending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='top_spending/')),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spending_date', models.DateField()),
            ],
            options={
                'ordering': ['-amount'],
            },
        ),
    ]
