# Generated by Django 6.0.3 on 2026-06-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0010_smartinsight_topspending'),
    ]

    operations = [
        migrations.AddField(
            model_name='topspending',
            name='name',
            field=models.CharField(default='Unknown', max_length=150),
        ),
    ]
