# Generated by Django 6.0.3 on 2026-06-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0011_topspending_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='budgets/')),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('near_limit', 'Near Limit'), ('safe', 'Safe')], default='safe', max_length=20)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
