# Generated by Django 6.0.3 on 2026-06-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0013_accountsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bank_accounts/')),
                ('bank_name', models.CharField(max_length=150)),
                ('account_type', models.CharField(choices=[('Savings Account', 'Savings Account'), ('Current Account', 'Current Account'), ('Salary Account', 'Salary Account')], default='Savings Account', max_length=50)),
                ('account_id', models.CharField(help_text='Example: XXXXXXXX12', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['bank_name'],
            },
        ),
    ]
