# Generated by Django 6.0.3 on 2026-06-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0014_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_category',
            field=models.CharField(choices=[('bank', 'Bank Accounts'), ('upi', 'UPI Accounts'), ('credit', 'Credit Cards')], default='bank', max_length=20),
        ),
    ]
